# -*- coding: utf-8 -*-
"""
/***************************************************************************
 area_buffer
                                 A QGIS plugin
 Los usuarios de QGIS frecuentemente necesitan crear buffers en torno a puntos temporales para sus análisis geoespaciales, sin embargo, la herramienta de geoproceso "buffer", que por defecto posee QGIS, puede ser compleja y requiere varios pasos y parámetros que pueden ser innecesarios para tareas simples. Se necesita un plugin que simplifique este proceso, permitiendo a los usuarios crear un punto temporal y definir el tamaño del buffer de manera rápida e intuitiva, sin tener que manejar todos los parámetros de la herramienta estándar de QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-07
        copyright            : (C) 2024 by Nicolas Chaparro, Sergio Acuña
        email                : sscunav@udistrital.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load area_buffer class from file area_buffer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .generador_buffer import area_buffer
    return area_buffer(iface)
