# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generador_buffer_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneradorBufferDialogBase(object):
    def setupUi(self, GeneradorBufferDialogBase):
        GeneradorBufferDialogBase.setObjectName("GeneradorBufferDialogBase")
        GeneradorBufferDialogBase.resize(423, 237)
        self.S_groupBox = QtWidgets.QGroupBox(GeneradorBufferDialogBase)
        self.S_groupBox.setGeometry(QtCore.QRect(10, 30, 251, 81))
        self.S_groupBox.setObjectName("S_groupBox")
        self.label = QtWidgets.QLabel(self.S_groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.S_groupBox)
        self.pushButton.setGeometry(QtCore.QRect(110, 40, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.B_groupBox = QtWidgets.QGroupBox(GeneradorBufferDialogBase)
        self.B_groupBox.setGeometry(QtCore.QRect(279, 19, 131, 91))
        self.B_groupBox.setObjectName("B_groupBox")
        self.pushButton_5 = QtWidgets.QPushButton(self.B_groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 50, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox = QtWidgets.QGroupBox(GeneradorBufferDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(10, 120, 401, 101))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 70, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(192, 40, 161, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 171, 20))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(GeneradorBufferDialogBase)
        QtCore.QMetaObject.connectSlotsByName(GeneradorBufferDialogBase)

    def retranslateUi(self, GeneradorBufferDialogBase):
        _translate = QtCore.QCoreApplication.translate
        GeneradorBufferDialogBase.setWindowTitle(_translate("GeneradorBufferDialogBase", "Generador de Buffer"))
        self.S_groupBox.setTitle(_translate("GeneradorBufferDialogBase", "Selección"))
        self.label.setText(_translate("GeneradorBufferDialogBase", "Punto buffer:"))
        self.pushButton.setText(_translate("GeneradorBufferDialogBase", "Pulsar"))
        self.B_groupBox.setTitle(_translate("GeneradorBufferDialogBase", "Borrar"))
        self.pushButton_5.setText(_translate("GeneradorBufferDialogBase", "Borrar"))
        self.groupBox.setTitle(_translate("GeneradorBufferDialogBase", "Generación Buffer"))
        self.pushButton_2.setText(_translate("GeneradorBufferDialogBase", "Buffer"))
        self.label_2.setText(_translate("GeneradorBufferDialogBase", "Tamaño buffer (Area):"))
